export const data = [
  "We are creating a league where you can play football and fill your desire of getting back on the field. The league will consist of many different players who come from all backgrounds.",
  "After applying you will be assigned to a team where you can cordinate practices and work together to create a team that stands out from the rest. Each player will be given gear so they can play safely. Feel free to customize you gear to promote or advertise certain brands or organizations. Work hard and show good sportmanship and you might gather the attention from people watching who might take an interest in what you're promoting.",
  "You can apply now! We will ask you to fill out a form regarding some information that will help us get an idea of who you are and where you're coming from. All this information will be safe and stay within our records. We will only disclose information like your name, and contant info, so your team can get ahold of you and address you properly.",
];

export const lora = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  "Enim tortor at auctor urna nunc id cursus metus aliquam. Sit amet dictum sit amet justo donec. Senectus et netus et malesuada fames ac. Non tellus orci ac auctor. Eu volutpat odio facilisis mauris. Eget nullam non nisi est. Consectetur adipiscing elit ut aliquam purus sit. Quis lectus nulla at volutpat diam ut venenatis. Dui sapien eget mi proin sed. Consectetur purus ut faucibus pulvinar. Blandit volutpat maecenas volutpat blandit aliquam etiam. Et ultrices neque ornare aenean euismod elementum nisi. Nisi est sit amet facilisis magna etiam tempor orci. Vestibulum sed arcu non odio euismod lacinia at quis risus. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ultricies lacus sed turpis tincidunt id aliquet. Id aliquet lectus proin nibh nisl. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam. Etiam sit amet nisl purus.",
  "Dui accumsan sit amet nulla facilisi morbi. Erat imperdiet sed euismod nisi. Sed arcu non odio euismod lacinia at quis risus sed. Pharetra convallis posuere morbi leo urna molestie. Nunc aliquet bibendum enim facilisis gravida neque. Arcu ac tortor dignissim convallis. Hendrerit dolor magna eget est lorem ipsum dolor sit amet. Mauris vitae ultricies leo integer malesuada nunc. Amet mattis vulputate enim nulla aliquet porttitor. Vitae congue mauris rhoncus aenean. Ut morbi tincidunt augue interdum velit euismod. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Commodo viverra maecenas accumsan lacus vel. Lobortis elementum nibh tellus molestie nunc. Laoreet id donec ultrices tincidunt arcu non. Sagittis vitae et leo duis ut diam quam. Sed velit dignissim sodales ut eu.",
  "Ac turpis egestas sed tempus urna et. Gravida arcu ac tortor dignissim convallis aenean. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non. Dignissim sodales ut eu sem integer vitae justo. Tristique magna sit amet purus gravida quis blandit turpis cursus. Nec feugiat nisl pretium fusce id. Mauris ultrices eros in cursus turpis massa tincidunt dui. Enim praesent elementum facilisis leo vel fringilla est ullamcorper. Egestas diam in arcu cursus euismod quis viverra. Elit eget gravida cum sociis natoque penatibus et magnis dis. Malesuada pellentesque elit eget gravida. Ut eu sem integer vitae. Eget gravida cum sociis natoque penatibus et magnis. Sed nisi lacus sed viverra tellus.",
];
