export const rulesData = [
  "We (Fanatics Football) play by a combination of the common and basic rules of football as practiced by the National Federation of State High School Associations (NFHS), National Collegiate Athletic Association (NCAA), and the National Football League (NFL). By participating, it is conclusively presumed that each participant understands and follows/will follow the basic, fundamental, rules of football. In addition to the previously mentioned, the following rules are recognized, practiced, and enforced by Fanatics Football:",
  [
    "Ball is placed/kickoff at 35-yard line.",
    "Players may get a running start before kickoff, but must remain behind the Line of Scrimmage until the ball is kicked.",
    "Ball is kicked into the Endzone/Fair Catch in the Endzone (Touchback), ball is placed at the 25 yard-line",
    "Fair Catch outside of the Endzone – ball is placed at the Fair Catch spot.",
    "Return Team may create a 'wedge' of up to 3 players/blockers.",
    "Drop-Kick is allowed for Kickoff.",
  ],
  [
    "Players may get a running start before Onside kick, but must remain behind the Line of Scrimmage until the ball is kicked.",
    "Kicking Team may 'overload' one side of the ball up to 10 players on one side",
    "Kicking Team may engage Receiving Team before the ball passes 10 yards",
    "Kicking Team may engage Receiving Team before any player on the Receiving Team touches the ball.",
    "Drop-Kick is allowed for Onside Kick.",
  ],
  [
    "Offence may have up to 2 Gunners",
    "Only Gunner(s) may proceed downfield after the ball is snapped; every other offensive player must stay at/behind the Line of Scrimmage until the ball is punted/kicked.",
    "Drop-Kick is allowed for Punting",
  ],
  [
    "Ball placed at 5-yard line & anywhere between the hash marks.",
    "Drop-Kick is allowed for PAT.",
  ],
  [
    "Ball placed at 20-yard line for the Kicking Team.",
    "Kicking Team may Punt, Drop-Kick, Kickoff, or Onside Kick.",
  ],
  [
    "A ball carrier may use hands to the face and grab the face mask of a “would be tackler.”",
    "Receiver must have at least one foot in-bounds in order for the pass to be completed.",
    "If the receiver catches the ball in the air, but is pushed out of before the receiver gets one foot in bounds, the pass is incomplete.",
    "Receiver must “survive the ground” in order for the pass to be completed.",
    "Receiver must make a “football move” in order for the pass to be completed.",
    "The ground can not cause a fumble",
  ],
  [
    "Chop-Blocking/High-Low Blocking is not allowed and is penalized with a Personal Foul & a 15-yard penalty.",
    "The “Free Blocking Zone” (FBZ) is defined & is illustrated in Exhibit A.",
    "Cut Blocking/Cutting is only allowed in the FBZ.",
    "All other blocks/eliminating a lead blocker(s), outside of the FBZ, must be engaged at/above the hip.",
    "Penalties for “Blind Side” block(s)/hit(s) do not exist. Keep your head on a swivel.",
  ],
  [
    "Quarterbacks can be hit/tackled, but don’t go low on purpose; we’re all friends. If an Official/Referee determines that a player(s) intentionally “went low” on a Quarterback with ill intent, the Official/Referee will penalize said player(s) with a Personal Foul (15-yard penalty) and an automatic 1st Down for the Offense.",
    "Defenders are allowed to defend the pass without turning around to look at the ball (i.e., putting your hands up while your back is toward the ball).",
    "“Re-Routes” (pressing/blocking/hitting a receiver) is allowed, anywhere on the field, until the ball is in the air.",
    "Defenders may hit/tackle a receiver that is behind the line of scrimmage (i.e., a play action pass where a full back is going to go out in to the flat or a running back/receiver is going out for a screen). Once the receiver reaches the line of scrimmage, the “ReRoute” rule goes in to affect.",
    "“Targeting” does not exist.",
    "Hitting a “Defenseless Receiver” does not exist.",
    "There is/are no penalties for: Tackling in the head or neck area; Contact with the head or neck area; Leading with the head/crown of the helmet; Helmet to Helmet contact.",
  ],
  [
    "Pat McAfee Overtime",
    "One, 10-minute Quarter (Classic Football)",
    "If tied after said Quarter: 2-Point Conversion Sudden-Death Shootout (up to 3 rounds).",
    "If tied at the end of said Shootout: Kicker Duel – Start from 10-yard line, then 20-yard line, then 30-yard line, continuing back in 10-yard increments after each kick is made. Each Kicker gets one attempt per distance. If both kickers miss at the same distance, both kickers will get to attempt the kick again. If both kickers miss again (miss second attempt), the Kicker Duel ends in a tie.",
    "If tied at the end of said Kicker Duel: Kicker “HORSE” – Kickers have to kick the ball between the uprights while kicking from anywhere on the field, so long as the kicker (and Holder if applicable) are in-bounds while the kick is being performed (Kickers may kick from outside the hashmarks and from the inside the End-Zone). Kicker “HORSE” follows the traditional rules of HORSE, but this is One & Done; meaning once a Kicker gets an “H,” that kicker loses and the game is over; leaving the team with the winning Kicker as the victor of the entire Game.",
    "Drop-Kick is allowed for Kicker Duel & Kicker “HORSE.”",
  ],
  [
    "Horse Collar tackling is a Personal Foul (15-yard penalty) and an automatic 1st Down.",
    "If Defensive Pass Interference occurs in the End-Zone, the ball is to be placed at the defensive 5-yard line with a new Set of Downs.",
    "The Game/Overtime may not end on a penalty that impacts the outcome of said Game/Overtime (i.e., an incomplete pass due to defensive pass interference or a touchdown pass, but there is an offensive hold on the play).",
  ],
  [
    "Top 4 teams advance to the Playoffs (in the event of a tie, the team(s) with the most points scored, during regulation time, will advance to the Playoffs).",
    "There is 1 Playoff Game.",
    "The 2 teams that win their Playoff Game, advance to the Championship Game",
    "The team that wins the Championship Game, are the Champions.",
  ],
];
